name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Run the tests
        run: platformio test

      - name: Build the examples
        run: ./build_examples.sh
